{
 "title": "Raspberry Pi 5",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total MEM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disks Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Logical CPUs Number",
   "type": "stat",
   "description": "🔧 Physical Cores\nEach core has its own execution unit.\n\nCan run one thread at full speed.\n\nIdeal for parallel workloads like AI inference, video encoding, or compiling.\n\n🧪 Logical Cores\nCreated by splitting a physical core into two threads.\n\nShare resources (cache, execution units), so performance per thread is lower.\n\nUseful for multitasking, I/O-bound workloads, or keeping the CPU busy while one thread stalls.\n\nThink of physical cores as full-time workers, and logical cores as interns sharing desks — helpful, but not independent.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "description": "\nField Name\tWhat It Tells You\tWhy It Matters\ntotal\tTotal number of processes\tOverall system load\nrunning\tActively executing processes\tReal-time demand\nsleeping\tProcesses waiting for events\tNormal for idle apps\nblocked\tUninterruptible sleep (usually I/O wait)\tDetects disk/network bottlenecks\nidle\tTruly idle processes\tHelps distinguish from sleeping\nstopped\tManually or system-stopped processes\tCan indicate crashes or admin actions\nzombies\tDefunct processes not cleaned up\tSignals poor process hygiene\ntotal_threads\tTotal number of threads across all processes\tShows concurrency and thread pressure",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"running\" or r[\"_field\"] == \"sleeping\" or r[\"_field\"] == \"blocked\" or r[\"_field\"] == \"idle\" or r[\"_field\"] == \"stopped\" or r[\"_field\"] == \"zombies\" or r[\"_field\"] == \"total_threads\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "MEM Available / Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"available\" or r[\"_field\"] == \"used\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MEM Available / Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\" or r[\"_field\"] == \"available_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Swap Free / Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_free\" or r[\"_field\"] == \"swap_total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "System / User usage %",
     "type": "timeseries",
     "description": "\nusage_user\t% of CPU time spent on user-level processes\tShows app and workload activity\nusage_system\t% of CPU time spent on kernel/system processes\tReveals OS and driver overhead",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Usage Idle %",
     "type": "timeseries",
     "description": "The percentage of time the CPU isn’t doing anything — no user tasks, no system calls, just waiting.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Usage IO Wait %",
     "type": "timeseries",
     "description": "What it means: Time the CPU spends waiting for I/O operations to complete — usually disk or network.\n\nWhy it matters:\n\nHigh iowait means your CPU is ready, but storage or network is dragging.\n\nIt’s a red flag for disk-bound workloads, slow SSDs, or overloaded buses.\n\nUse it to:\n\nDiagnose sluggishness in data-heavy tasks.\n\nValidate SSD upgrades or disk optimizations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_iowait\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Disks Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Disks Used %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "DisksIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks IO Read / Write",
     "type": "timeseries",
     "description": "Shows throughput",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\" or r[\"_field\"] == \"write_bytes\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> difference()\r\n  |> yield(name: \"rate\")\r\n"
      }
     ]
    },
    {
     "title": "Disks IO Time",
     "type": "timeseries",
     "description": "Total time spent on I/O operations (ms)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"io_time\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
      }
     ]
    },
    {
     "title": "Disks Weighted IO Time",
     "type": "timeseries",
     "description": "It’s the total time that I/O requests have waited on a block device, but with a twist: It’s weighted by the number of concurrent requests.\n\nSo if:\n\n1 request waits for 100 ms → weighted_io_time = 100\n\n10 requests each wait for 100 ms → weighted_io_time = 1000\n\nIt’s not just how long the disk was busy — it’s how intensely it was busy.\n\n🔍 Why It Matters\nHigh weighted_io_time means your disk is under heavy load — not just active, but stacked with queued requests\n\nIt’s a great indicator of I/O contention, especially on slow media like SD cards or USB drives\n\nIt complements io_time, which only tracks whether the disk was doing any I/O, not how many requests were stacked",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_io_time\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
      }
     ]
    },
    {
     "title": "iops in progress",
     "type": "timeseries",
     "description": "It represents the number of I/O operations currently being processed by the disk at a given instant.\n\nThese include reads and writes that have been issued but not yet completed.\n\nIt’s a snapshot, not a cumulative counter — like peeking into the disk’s task queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"RaspberryPI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iops_in_progress\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}